# Generated by Django 3.1.5 on 2021-02-24 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_auto_20210218_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='feed_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.news_category'),
        ),
    ]
